services:
  drawer:
    build:
      context: ./drawer
    ports:
      - 8000:80
  sort:
    build:
      context: ./sort
    ports:
      - 8001:80
  console:
    build:
      context: ./console
    ports:
      - 8002:80

