services:
  db:
    image: mysql
    container_name: 5sem-servers-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  reverse-proxy:
    image: nginx
    container_name: 5sem-servers-reverse-proxy
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx-default.conf:/etc/nginx/conf.d/nginx-default.conf
    ports:
      - "80:80"
      - "8080:8080"
      - "8081:8081"
    restart: always
  apache-server:
    build: dynamic/Dockerfile
    container_name: 5sem-servers-php-apache-server
    volumes:
      - ./dynamic/src:/var/www/html/
    depends_on:
      - db
      - reverse-proxy

  nginx-server:
    image: nginx
    container_name: 5sem-servers-nginx-server
    volumes:
      - ./static:/usr/share/nginx/html
    depends_on:
      - reverse-proxy

