services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: dungeonmaster
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
  server:
    build: .
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/

