services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: dungeonmaster
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    build: .
    ports:
      - 80:80
    depends_on:
      - db

